title: Advanced Python Programming
description: Kevin Michoud & Pierre Pelletier
baseurl: "/advanced_programming_python"
url: "https://knuxv.github.io"
author:
  name: Kevin Michoud

markdown: kramdown
highlighter: rouge
theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-jupyter-notebook

minima:
  skin: auto
  social_links:
    github: KnuxV

# Optional: show selected pages in the header nav
header_pages:
  - index.md

# Force all pages to use our custom default layout
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: "lessons"
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: "exercices"
      type: "pages"
    values:
      layout: "default"
