title: Advanced Python Programming
description: Economics Master - Python Course
baseurl: "/your-repo-name"
url: "https://yourusername.github.io"

markdown: kramdown
highlighter: rouge
theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap