title: Advanced Python Programming
description: September 2025
baseurl: "/advanced_programming_python"
url: "https://knuxv.github.io"
author:
  Kevin Michoud & Pierre Pelletier

markdown: kramdown
highlighter: rouge
theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-jupyter-notebook

minima:
  skin: auto
  social_links:
    github: KnuxV

# Optional: show selected pages in the header nav
header_pages:
  - index.md

# Force all pages to use our custom page layout (which includes content-wrapper)
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: "lessons"
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: "exercices"
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: "code-examples"
      type: "pages"
    values:
      layout: "page"